import 'package:flutter/material.dart';
import 'package:flutterapp/proyecto_finalapp/generatedajusteswidget5/generated/GeneratedRectangle17Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedajusteswidget5/generated/GeneratedRectangle15Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedajusteswidget5/generated/GeneratedHomesharpWidget6.dart';
import 'package:flutterapp/proyecto_finalapp/generatedajusteswidget5/generated/GeneratedCambiartarjetadecreditoWidget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedajusteswidget5/generated/GeneratedRectangle13Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedajusteswidget5/generated/GeneratedRectangle14Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedajusteswidget5/generated/GeneratedCardWidget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedajusteswidget5/generated/GeneratedRectangle16Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedajusteswidget5/generated/GeneratedFrame6Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedajusteswidget5/generated/GeneratedVectorWidget45.dart';
import 'package:flutterapp/proyecto_finalapp/generatedajusteswidget5/generated/GeneratedAJUSTESWidget.dart';

/* Frame Ajustes
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAjustesWidget5 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 8.0,
                top: 566.0,
                right: null,
                bottom: null,
                width: 344.0,
                height: 74.0,
                child: GeneratedFrame6Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 50.0,
                child: GeneratedRectangle13Widget(),
              ),
              Positioned(
                left: 129.0,
                top: 5.0,
                right: null,
                bottom: null,
                width: 107.0,
                height: 45.0,
                child: GeneratedAJUSTESWidget(),
              ),
              Positioned(
                left: 26.0,
                top: 68.0,
                right: null,
                bottom: null,
                width: 308.0,
                height: 62.0,
                child: GeneratedRectangle14Widget(),
              ),
              Positioned(
                left: 26.0,
                top: 177.0,
                right: null,
                bottom: null,
                width: 308.0,
                height: 62.0,
                child: GeneratedRectangle15Widget(),
              ),
              Positioned(
                left: -196.0,
                top: 98.0,
                right: null,
                bottom: null,
                width: 517.0,
                height: 518.0,
                child: GeneratedCardWidget(),
              ),
              Positioned(
                left: 26.0,
                top: 289.0,
                right: null,
                bottom: null,
                width: 308.0,
                height: 62.0,
                child: GeneratedRectangle16Widget(),
              ),
              Positioned(
                left: 24.0,
                top: 401.0,
                right: null,
                bottom: null,
                width: 308.0,
                height: 62.0,
                child: GeneratedRectangle17Widget(),
              ),
              Positioned(
                left: 86.0,
                top: 90.0,
                right: null,
                bottom: null,
                width: 229.0,
                height: 20.0,
                child: GeneratedCambiartarjetadecreditoWidget(),
              ),
              Positioned(
                left: 38.0,
                top: 82.0,
                right: null,
                bottom: null,
                width: 38.0,
                height: 34.0,
                child: GeneratedVectorWidget45(),
              ),
              Positioned(
                left: -56.203857421875,
                top: 195.204345703125,
                right: null,
                bottom: null,
                width: 512.0,
                height: 512.0,
                child: GeneratedHomesharpWidget6(),
              )
            ]),
      ),
    ));
  }
}
