import 'package:flutter/material.dart';
import 'package:flutterapp/proyecto_finalapp/generatedtelefonoswidget4/generated/GeneratedCelularWidget2.dart';
import 'package:flutterapp/proyecto_finalapp/generatedtelefonoswidget4/generated/GeneratedOppoa93128Gbazul1Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedtelefonoswidget4/generated/GeneratedTelefonosalaventaWidget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedtelefonoswidget4/generated/GeneratedFrame5Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedtelefonoswidget4/generated/GeneratedSamsungnote10LiteN7701Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedtelefonoswidget4/generated/GeneratedRectangle11Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedtelefonoswidget4/generated/GeneratedCelularWidget1.dart';
import 'package:flutterapp/proyecto_finalapp/generatedtelefonoswidget4/generated/GeneratedCelularWidget.dart';

/* Frame Telefonos
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTelefonosWidget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 8.0,
                top: 566.0,
                right: null,
                bottom: null,
                width: 344.0,
                height: 74.0,
                child: GeneratedFrame5Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 50.0,
                child: GeneratedRectangle11Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 362.0,
                height: 52.0,
                child: GeneratedTelefonosalaventaWidget(),
              ),
              Positioned(
                left: 15.0,
                top: 77.0,
                right: null,
                bottom: null,
                width: 324.0,
                height: 136.0,
                child: GeneratedCelularWidget(),
              ),
              Positioned(
                left: 15.0,
                top: 252.0,
                right: null,
                bottom: null,
                width: 324.0,
                height: 136.0,
                child: GeneratedCelularWidget1(),
              ),
              Positioned(
                left: 15.0,
                top: 409.0,
                right: null,
                bottom: null,
                width: 324.0,
                height: 136.0,
                child: GeneratedCelularWidget2(),
              ),
              Positioned(
                left: 182.0,
                top: 276.0,
                right: null,
                bottom: null,
                width: 143.0,
                height: 88.0,
                child: GeneratedSamsungnote10LiteN7701Widget(),
              ),
              Positioned(
                left: 233.0,
                top: 427.0,
                right: null,
                bottom: null,
                width: 81.0,
                height: 105.0,
                child: GeneratedOppoa93128Gbazul1Widget(),
              )
            ]),
      ),
    ));
  }
}
