import 'package:flutter/material.dart';
import 'package:flutterapp/proyecto_finalapp/generatedusuariowidget3/generated/GeneratedBotonWidget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedusuariowidget3/generated/GeneratedUsuarioUsuaWidget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedusuariowidget3/generated/GeneratedRectangle9Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedusuariowidget3/generated/GeneratedBotonWidget2.dart';
import 'package:flutterapp/proyecto_finalapp/generatedusuariowidget3/generated/GeneratedBotonWidget3.dart';
import 'package:flutterapp/proyecto_finalapp/generatedusuariowidget3/generated/GeneratedBotonWidget1.dart';
import 'package:flutterapp/proyecto_finalapp/generatedusuariowidget3/generated/GeneratedFrame4Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatedusuariowidget3/generated/GeneratedVectorWidget31.dart';
import 'package:flutterapp/proyecto_finalapp/generatedusuariowidget3/generated/GeneratedVectorWidget30.dart';

/* Frame Usuario
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedUsuarioWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 8.0,
                top: 566.0,
                right: null,
                bottom: null,
                width: 344.0,
                height: 74.0,
                child: GeneratedFrame4Widget(),
              ),
              Positioned(
                left: 21.0,
                top: 99.0,
                right: null,
                bottom: null,
                width: 322.0,
                height: 63.0,
                child: GeneratedBotonWidget(),
              ),
              Positioned(
                left: 21.0,
                top: 206.0,
                right: null,
                bottom: null,
                width: 452.0,
                height: 719.0,
                child: GeneratedBotonWidget1(),
              ),
              Positioned(
                left: 21.0,
                top: 314.0,
                right: null,
                bottom: null,
                width: 322.0,
                height: 63.0,
                child: GeneratedBotonWidget2(),
              ),
              Positioned(
                left: 21.0,
                top: 430.0,
                right: null,
                bottom: null,
                width: 322.0,
                height: 63.0,
                child: GeneratedBotonWidget3(),
              ),
              Positioned(
                left: 0.0,
                top: -1.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 69.0,
                child: GeneratedRectangle9Widget(),
              ),
              Positioned(
                left: 121.0,
                top: 9.0,
                right: null,
                bottom: null,
                width: 130.0,
                height: 77.03389739990234,
                child: GeneratedUsuarioUsuaWidget(),
              ),
              Positioned(
                left: 50.0,
                top: 215.0,
                right: null,
                bottom: null,
                width: 34.0,
                height: 45.999996185302734,
                child: GeneratedVectorWidget30(),
              ),
              Positioned(
                left: 44.0,
                top: 323.0,
                right: null,
                bottom: null,
                width: 46.0,
                height: 46.0,
                child: GeneratedVectorWidget31(),
              )
            ]),
      ),
    ));
  }
}
