import 'package:flutter/material.dart';
import 'package:flutterapp/proyecto_finalapp/generatediniciowidget2/generated/GeneratedAmigo1Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatediniciowidget2/generated/GeneratedFrame2Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatediniciowidget2/generated/GeneratedRectangle7Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatediniciowidget2/generated/GeneratedCambiateaamigokitEslacoberturamasgrandeyrapidaentodomex.dart';
import 'package:flutterapp/proyecto_finalapp/generatediniciowidget2/generated/GeneratedTELCELESLAREDWidget.dart';
import 'package:flutterapp/proyecto_finalapp/generatediniciowidget2/generated/GeneratedRectangle8Widget.dart';
import 'package:flutterapp/proyecto_finalapp/generatediniciowidget2/generated/GeneratedChip1Widget.dart';

/* Frame Inicio
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedInicioWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 8.0,
                top: 566.0,
                right: null,
                bottom: null,
                width: 344.0,
                height: 74.0,
                child: GeneratedFrame2Widget(),
              ),
              Positioned(
                left: 1.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 55.0,
                child: GeneratedRectangle7Widget(),
              ),
              Positioned(
                left: 32.0,
                top: 9.0,
                right: null,
                bottom: null,
                width: 302.0,
                height: 31.0,
                child: GeneratedTELCELESLAREDWidget(),
              ),
              Positioned(
                left: 10.0,
                top: 70.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 124.0,
                child: GeneratedRectangle8Widget(),
              ),
              Positioned(
                left: 7.0,
                top: 70.0,
                right: null,
                bottom: null,
                width: 345.0,
                height: 222.0,
                child:
                    GeneratedCambiateaamigokitEslacoberturamasgrandeyrapidaentodomex(),
              ),
              Positioned(
                left: 253.0,
                top: 74.0,
                right: null,
                bottom: null,
                width: 86.0,
                height: 36.0,
                child: GeneratedAmigo1Widget(),
              ),
              Positioned(
                left: 10.0,
                top: 202.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 328.0,
                child: GeneratedChip1Widget(),
              )
            ]),
      ),
    ));
  }
}
