import 'package:flutter/material.dart';
import 'package:flutterapp/proyecto_finalapp/generatedframe1widget/generated/GeneratedInformationcircleWidget1.dart';
import 'package:flutterapp/proyecto_finalapp/generatedframe1widget/generated/GeneratedIconsWidget1.dart';
import 'package:flutterapp/proyecto_finalapp/generatedframe1widget/generated/GeneratedUsuarioWidget1.dart';
import 'package:flutterapp/proyecto_finalapp/generatedframe1widget/generated/GeneratedHomesharpWidget1.dart';
import 'package:flutterapp/proyecto_finalapp/generatedframe1widget/generated/GeneratedInicioWidget1.dart';
import 'package:flutterapp/proyecto_finalapp/generatedframe1widget/generated/GeneratedTelefonosWidget1.dart';
import 'package:flutterapp/proyecto_finalapp/generatedframe1widget/generated/GeneratedAjustesWidget1.dart';
import 'package:flutterapp/proyecto_finalapp/generatedframe1widget/generated/GeneratedInformacionWidget1.dart';
import 'package:flutterapp/proyecto_finalapp/generatedframe1widget/generated/GeneratedVectorWidget9.dart';
import 'package:flutterapp/proyecto_finalapp/generatedframe1widget/generated/GeneratedVectorWidget10.dart';

/* Component Frame 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 344.0,
      height: 74.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 344.0,
              height: 74.0,
              child: GeneratedIconsWidget1(),
            ),
            Positioned(
              left: 75.0,
              top: 52.0,
              right: null,
              bottom: null,
              width: 67.0,
              height: 16.0,
              child: GeneratedInformacionWidget1(),
            ),
            Positioned(
              left: 24.0,
              top: 52.0,
              right: null,
              bottom: null,
              width: 30.0,
              height: 16.0,
              child: GeneratedInicioWidget1(),
            ),
            Positioned(
              left: 157.0,
              top: 52.0,
              right: null,
              bottom: null,
              width: 43.0,
              height: 16.0,
              child: GeneratedUsuarioWidget1(),
            ),
            Positioned(
              left: 225.0,
              top: 52.0,
              right: null,
              bottom: null,
              width: 55.0,
              height: 16.0,
              child: GeneratedTelefonosWidget1(),
            ),
            Positioned(
              left: 296.0,
              top: 51.0,
              right: null,
              bottom: null,
              width: 44.0,
              height: 16.0,
              child: GeneratedAjustesWidget1(),
            ),
            Positioned(
              left: 23.0,
              top: 21.0,
              right: null,
              bottom: null,
              width: 28.571428298950195,
              height: 25.0,
              child: GeneratedVectorWidget9(),
            ),
            Positioned(
              left: 23.0,
              top: 21.0,
              right: null,
              bottom: null,
              width: 29.0,
              height: 25.0,
              child: GeneratedHomesharpWidget1(),
            ),
            Positioned(
              left: 237.0,
              top: 21.0,
              right: null,
              bottom: null,
              width: 25.0,
              height: 25.0,
              child: GeneratedVectorWidget10(),
            ),
            Positioned(
              left: 84.0,
              top: 17.0,
              right: null,
              bottom: null,
              width: 38.0,
              height: 36.0,
              child: GeneratedInformationcircleWidget1(),
            )
          ]),
    ));
  }
}
